
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:10

before_script:
  - npm install

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

#build:
#  stage: build
#  script:
#    - npm build

#lin_test:
#  stage: test
#  script:
#    - npm lin

int_test:
  stage: test
  script:
    - npm test
  artifacts:
    paths:
      - coverage

#deploy_code:
#  stage: deploy
#  only:
#    - master
#  script:
#    - echo 'command deploy here.'

after_script:
  - echo 'USE CASE ALL SCENARIO PASS.'
